# These are supported funding model platforms

github: [erilshackle]
buy_me_a_coffee: erilcarvalho # Se você tiver Buy Me a Coffee
custom: ['https://www.linkedin.com/in/erilcarvalho/', 'https://github.com/erilshackle']
